import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from "../components/navbar/nav-bar";
import Search from "../components/searchpage/Search"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Github</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="theme-color" content="#161e29"/>
                <link rel="icon" href="/download.png"/>
                <style jsx global>{`body {background:#161e29 };}`}</style>
            </Head>
            <NavBar/>
            <div className={styles.title}>
                <div>GitHub User Finder</div>
            </div>
            <Search/>

        </div>
    )
}
